charon {
    # load_modular = yes
    # plugins {
    #     include /usr/local/etc/strongswan.d/charon/*.conf
    # }

    dns_resolver {
        interval = 300
    }

    # Infinite retries during long WAN drops
    retransmit_tries = 0
    retransmit_timeout = 4.0
    retransmit_base = 1.8
}

connections {
    paloalto-hub {
        version = 2
        # IKE Suite-B-GCM-256: AES-256-CBC, SHA384, DH Group 20 (ecp384)
        proposals = aes256-sha384-ecp384
        # proposals = aes256gcm16-prfsha384-ecp384-ke1_mlkem768, aes256gcm16-prfsha384-curve25519-ke1_mlkem768

        # Endpoints
        local_addrs = %defaultroute
        remote_addrs = changeme_hub.tld

        # Identifications
        local {
            auth = psk
            id = changeme_spoke.tld
        }
        remote {
            auth = psk
            id = changeme_hub.tld
        }

        children {
            paloalto-tunnel {
                # IPsec Suite-B-GCM-256: ESP, AES-256-GCM (16-byte ICV), DH Group 20 (ecp384)
                esp_proposals = aes256gcm16-sha384

                # Bind to XFRM interface ID 42
                if_id_in = 42
                if_id_out = 42

                # Traffic Selectors (See Note Below)
                local_ts = 0.0.0.0/0
                remote_ts = 0.0.0.0/0

                # IPsec Lifetime: 1 hour (3600s), rekeying slightly before expiry
                rekey_time = 3000s # When StrongSwan attempts to negotiate a replacement IPsec SA before the 1-hour expiration
                life_time = 3600s # IPSec Crypto Profiles > Key Lifetime. Hard lifetime of Phase 2 (Data Tunnel / Child SA).
                rand_time = 300s

                # Resiliency triggers
                start_action = trap
                close_action = start
                dpd_action = restart
            }
        }

        # --- RFC 8784 Post-Quantum PSK (PPK) ---
        ppk_id = changeme_pq-id-spoke-hub
        ppk_required = yes

        # --- IKE Lifetime & Resiliency (8 hours) ---
        reauth_time = 0 # Disables re-authentication so rekeying happens seamlessly in the background without dropping the tunnel
        rekey_time = 25200s # StrongSwan proactively generates new IKE keys before the 8h Palo Alto limit hits
        over_time = 28800s # Relates to IKE Crypto Profiles > Key Lifetime
        dpd_delay = 20s # IKE Gateways > Advanced Options > Dead Peer Detection: Interval (default 5s)
        dpd_timeout = 120s # IKE Gateways > Advanced Options > DPD: Retry
    }
}

secrets {
    # 1. Classical IKEv2 Pre-Shared Key
    ike-classical {
        id-local = changeme_spoke.tld
        id-remote = changeme_hub.tld
        secret = "changeme_secret"
    }

    # 2. Post-Quantum Pre-Shared Key (PPK)
    ppk-putte {
        id = changeme_pq-id-spoke-hub
        secret = "changeme_secret"
    }
}